### ISSUE TITLE
Generate Go structs from Supabase tables

### ISSUE THREAD

**Issue by mmvergara** [supabase-community/supabase-go#15]
# Feature request

## Problem
The problem arised for us (in my job) always messes up the tables whenever we make a change and our codebase is large using this supabase go client. This problem I think is unique in my job only and people won't probably need this I'm just here to share the [**tool**](https://github.com/mmvergara/supabase-go-tables)
## Solution
I made a [**CLI**](https://github.com/mmvergara/supabase-go-tables) and [**Static site**](https://mmvergara.github.io/supabase-go-tables/) to generate go structs directly from the database 

```go
// It will generate this
type TableFormat struct {
    profiles string
    products string
}

var Tables = TableFormat{
    profiles: "profiles",
    products: "products",
}

// So instead of hardcoding table names directly:
// supabaseClient.From("profiles").Select("*").Execute()

// use the generate 'Tables' struct
supabaseClient.From(Tables.profiles).Select("*").Execute() 
```
So it's like achieving typesafety'ish like in Supabase TS
This way, if you make changes to your Supabase tables, you can simply regenerate the Go structs using the tool

This uses  the supabase API to fetch the tables just like this [Supabase Schema Visualizer App](https://supabase-schema.vercel.app/) so this thing probably will work forever unless the v1 api changes.

## Additional context
I'm proposing to somehow mention this tool  in the `Readme` of this repo, people may find it useful. I don't really mind if not im just here to share it.

**Comment by mmvergara** [comment]
will improve this further

**Comment by motatoes** [comment]
hey @mmvergara this is exactly what I was looking for! I noticed the repo no longer exists, any chance you can point me to where you have moved it to? Thanks!

**Comment by mmvergara** [comment]
> hey @mmvergara this is exactly what I was looking for! I noticed the repo no longer exists, any chance you can point me to where you have moved it to? Thanks!

Hey, i actually deleted the repository thinnking it is not so useful. but i restored it for you. links are now available
https://github.com/mmvergara/supabase-go-tables

**Comment by motatoes** [comment]
Thanks a lot!
