### ISSUE TITLE
Integrate with gotrue-go

### ISSUE THREAD

**Issue by elijahmorg** [supabase-community/supabase-go#8]
# Feature request

Integrate this supabase-go client with gotrue-go so that it can function more like an actual client. I plan on working on doing this and working towards adding feature parity with the supabase-js client.

## Is your feature request related to a problem? Please describe.

This client is not yet finished. I am going to push it towards being finished because I am bored.

## Describe the solution you'd like

I'll have to do some trial and error but for the most part I plan on making the api as similar to supabase-js as makes sense. Go is a very different language.

**Comment by jakeeknight** [comment]
Any time frame on this?

**Comment by jakeeknight** [comment]
Ah, I have integrated into my own internal package for now so thanks. Seems this and the postgrest-go repos aren't updated regularly which is a shame.

**Comment by tranhoangvuit** [comment]
I've tested with the newest version; it is already integrated with GoTrue. Thank @elijahmorg, I close this issue first.
